//@version=5
// This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License https://creativecommons.org/licenses/by-sa/4.0/
// © dman103
// My own interpretation of Multi time frame Moving averages momentum indicator with a variety of moving averages (Default EMA). The indicator checks the difference between two Moving Average and plots it as a Histogram.
// which can indicate the momentum of the current asset. The background does the same but with a higher time frame which can be set in the settings with AUTO (using Multiplier) or User-defined
// How to use the indicator?
// Histogram:
// Green: Momentum of asset is positive and increasing.
// Lighter Green: Momentum of asset is still positive but decreasing and can revert to negative momentum.
// Red: Momentum of asset is negative and increasing.
// Lighter Red: Momentum of asset is still negative but increasing and revert to positive momentum.
// Background:
// Green: HTF (Higher time frame) momentum is positive
// RED: HTF momentum is negative.
//
// Latest Script Updates:
// Added Buy/Sell Alerts. BUY alert when histogram crosses over zero line, SELL alert when histogram crosses under zero line.
// Upgrade to Pinescript v5 from v4.
// Optimized code.
// Improved settings usability. 
//
// Follow to get great upcoming updates & scripts: https://www.tradingview.com/u/dman103/#published-scripts
indicator(title='MA MTF Momentum Histogram', shorttitle='MA MTF Momentum Histogram', precision=3)

// Getting inputs
src = input(title='Source', defval=close)
ma_select = input.string(title='Moving Average Type', defval='SMMA', options=['SMA', 'EMA', 'WMA', 'HMA', 'JMA', 'TMA', 'VAMA', 'SMMA', 'DEMA', 'VMA', 'WWMA', 'EMA_NO_LAG', 'TSF'])  //DEFAULT INDICATOR EMA
fast_length = input(title='Fast Length', defval=4)  //DEFAULT INDICATOR 9
slow_length = input(title='Slow Length', defval=12)  //DEFAULT INDICATOR 12
htf_is_auto = input.string(title='Higher Timeframe Period', defval='Auto', options=['Auto', 'User Defined'], group="Higher Timeframe Main Trend (back color)")
res_multi = input.int(title='Auto Resolution Multiplier', defval=3, minval=1, group="Higher Timeframe Main Trend (back color)")
user_tf = input.timeframe(title='User Defined Timeframe', defval='120', group="Higher Timeframe Main Trend (back color)")

color_bars = input(title='Color bars', defval=false, group="Other Settings")
show_histogram = input(title='Show Histogram', defval=true, group="Other Settings")
show_lines = input(title='Show Lines', defval=true, group="Other Settings")
show_main_trend = input(title='Show main trend', defval=true, group="Other Settings")
volatility_lookback = input(title='Volatility lookback (only for VAMA)', defval=21, group="Other Settings")
///////Moving Averages
MA_selector(src, length) =>
    ma = 0.0
    if ma_select == 'SMA'
        ma := ta.sma(src, length)
        ma

    if ma_select == 'EMA'
        ma := ta.ema(src, length)
        ma

    if ma_select == 'WMA'
        ma := ta.wma(src, length)
        ma
    if ma_select == 'HMA'
        ma := ta.hma(src, length)
        ma
    if ma_select == 'JMA'
        beta = 0.45 * (length - 1) / (0.45 * (length - 1) + 2)
        alpha = beta
        tmp0 = 0.0
        tmp1 = 0.0
        tmp2 = 0.0
        tmp3 = 0.0
        tmp4 = 0.0
        tmp0 := (1 - alpha) * src + alpha * nz(tmp0[1])
        tmp1 := (src - tmp0[0]) * (1 - beta) + beta * nz(tmp1[1])
        tmp2 := tmp0[0] + tmp1[0]
        tmp3 := (tmp2[0] - nz(tmp4[1])) * (1 - alpha) * (1 - alpha) + alpha * alpha * nz(tmp3[1])
        tmp4 := nz(tmp4[1]) + tmp3[0]
        ma := tmp4
        ma
    if ma_select == 'TMA'
        ma := ta.sma(ta.sma(src, math.ceil(length / 2)), math.floor(length / 2) + 1)
        ma

    if ma_select == 'VMA'
        valpha = 2 / (length + 1)
        vud1 = src > src[1] ? src - src[1] : 0
        vdd1 = src < src[1] ? src[1] - src : 0
        vUD = math.sum(vud1, 9)
        vDD = math.sum(vdd1, 9)
        vCMO = nz((vUD - vDD) / (vUD + vDD))
        VAR = 0.0
        VAR := nz(valpha * math.abs(vCMO) * src) + (1 - valpha * math.abs(vCMO)) * nz(VAR[1])
        ma := VAR
        ma

    if ma_select == 'WWMA'
        wwalpha = 1 / length
        WWMA = 0.0
        WWMA := wwalpha * src + (1 - wwalpha) * nz(WWMA[1])
        ma := WWMA
        ma

    if ma_select == 'EMA_NO_LAG'
        EMA1 = ta.ema(src, length)
        EMA2 = ta.ema(EMA1, length)
        Difference = EMA1 - EMA2
        ma := EMA1 + Difference
        ma

    if ma_select == 'TSF'
        lrc = ta.linreg(src, length, 0)
        lrc1 = ta.linreg(src, length, 1)
        lrs = lrc - lrc1
        TSF = ta.linreg(src, length, 0) + lrs
        ma := TSF
        ma

    if ma_select == 'VAMA'  // Volatility Adjusted from @fractured
        mid = ta.ema(src, length)
        dev = src - mid
        vol_up = ta.highest(dev, volatility_lookback)
        vol_down = ta.lowest(dev, volatility_lookback)
        ma := mid + math.avg(vol_up, vol_down)
        ma
    if ma_select == 'SMMA'
        smma = float(0.0)
        smaval = ta.sma(src, length)
        smma := na(smma[1]) ? smaval : (smma[1] * (length - 1) + src) / length
        ma := smma
        ma

    if ma_select == 'DEMA'
        e1 = ta.ema(src, length)
        e2 = ta.ema(e1, length)
        ma := 2 * e1 - e2
        ma
    ma
f_multiple_resolution(_mult) =>
    target_Res_In_Min = timeframe.multiplier * _mult * (timeframe.isseconds ? 1. / 60. : timeframe.isminutes ? 1. : timeframe.isdaily ? 1440. : timeframe.isweekly ? 7. * 24. * 60. : timeframe.ismonthly ? 30.417 * 24. * 60. : na)

    target_Res_In_Min <= 0.0417 ? '1S' : target_Res_In_Min <= 0.167 ? '5S' : target_Res_In_Min <= 0.376 ? '15S' : target_Res_In_Min <= 0.751 ? '30S' : target_Res_In_Min <= 1440 ? str.tostring(math.round(target_Res_In_Min)) : str.tostring(math.round(math.min(target_Res_In_Min / 1440, 365))) + 'D'
res = htf_is_auto == 'Auto' ? f_multiple_resolution(res_multi) : user_tf

//  Colors
col_grow_above = #26A69A
col_grow_below = #FFCDD2
col_fall_above = #AAFFDB
col_fall_below = #EF5350

fast_ma = MA_selector(src, fast_length)
slow_ma = MA_selector(src, slow_length)

ma_diff = fast_ma - slow_ma

outma_diff = request.security(syminfo.tickerid, res, ma_diff[1], lookahead=barmerge.lookahead_on)
bcnt = 0
bcnt := ta.change(time(res)) != 0 ? 1 : nz(bcnt[1]) + 1
//Base MA Momentum
hist_color = ma_diff >= 0 ? ma_diff[1] < ma_diff ? col_grow_above : col_fall_above : ma_diff[1] < ma_diff ? col_grow_below : col_fall_below
plot(show_histogram ? ma_diff :  na, title='ma_diff', color= hist_color, style=plot.style_columns, linewidth=3)
plot(show_lines ? ma_diff: na, color=hist_color, linewidth=2)
//HTF MA Momentum for main trend
hist_color2 = outma_diff >= 0 ? nz(outma_diff[bcnt]) < outma_diff ? col_grow_above : col_fall_above : nz(outma_diff[bcnt]) < outma_diff ? col_grow_below : col_fall_below
bgcolor(show_main_trend ? outma_diff >= 0 ? color.new(color.green,93) : color.new(color.red,93) : na)
plot(0, color= color.new(color.blue,35))
plot(ma_diff >= 0 ? 1 : ma_diff < 0 ? -1 : na, display=display.none, title='Signal 1 or -1')
barcolor(color_bars ? hist_color : na)
long_alert = (ma_diff>=0 and ma_diff[1]<0)
short_alert = (ma_diff<=0 and ma_diff[1]>0)
alertcondition(long_alert, title='MTF Momentum Buy Signal', message='Buy Signal')
alertcondition(short_alert, title='MTF Momentum Sell Signal', message='Sell Signal')
